export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INCREASE_PRICE = "INCREASE_PRICE";
export const DECREASE_PRICE = "DECREASE_PRICE";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
